services:
  transacciones_backend:
    container_name: django_backend
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - django_redis
    env_file:
      - core/.env
    networks:
      - postgres_16_2-network

  django_redis:
    image: redis
    container_name: django_redis
    ports:
      - "6379:6379"
    networks:
      - postgres_16_2-network

networks:
  postgres_16_2-network:
    external: true
