# Generated by Django 5.2.1 on 2025-06-11 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-month'], 'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-date'], 'verbose_name': 'Tasa de cambio', 'verbose_name_plural': 'Tasas de cambio'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'currency', 'tag', 'month'), name='unique_budget_month_per_user_currency_tag_month'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'category_type'), name='unique_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base_currency', 'target_currency', 'date'), name='unique_exchange_rate_per_date'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tag_per_user'),
        ),
    ]
