# Generated by Django 5.2.1 on 2025-06-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_budget_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(related_name='transactions', to='transactions.tag'),
        ),
    ]
