# Generated by Django 5.2.1 on 2025-06-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('INGRESO', 'ingreso'), ('EGRESO', 'egreso')], default='INGRESO', max_length=10),
        ),
    ]
