# Generated by Django 5.2.1 on 2025-06-12 00:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_category_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'currency', 'tags', 'month')},
        ),
    ]
