# Generated by Django 5.2.1 on 2025-06-12 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_tag_budget_tags_alter_budget_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_month_per_user_currency_tag_month',
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'currency', 'tags', 'month'), name='unique_budget_month_per_user_currency_tag_month'),
        ),
    ]
